export const SAVE_PAYMENT_METHOD_REQUEST = 'SAVE_PAYMENT_METHOD_REQUEST';
export const SAVE_PAYMENT_METHOD_SUCCESS = 'SAVE_PAYMENT_METHOD_SUCCESS';
export const SAVE_PAYMENT_METHOD_FAIL = 'SAVE_PAYMENT_METHOD_FAIL';
